# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- Chernush

pool:
  name: default

variables:
  projectFolder: 'src/vue'
  buildOutputFolder: 'dist'

steps:
    - task: NodeTool@0
      inputs:
          versionSpec: '16.x'
      displayName: 'Install Node.js'
    # Building the package
    - script: |
          npm install
      displayName: 'npm install'

    - task: EvgenyChernyi.telegram-notification-extension.sample-telegram-task.SendTelegramNotification@0
      displayName: 'Send Telegram Notification'
      inputs:
        botToken: '5243205545:AAE9P1XSTX6y6vawii1kMTyd0lEi_35JOEc'
        chats: '-643936003'
        message: 'UNI Front Vue упал при установке пакетов'
        releaseName: true
        releaseRequestedFor: true
      continueOnError: true
      condition: failed()

    # Building the package
    - script: |
          npm run build
      displayName: 'npm run build'

    - task: EvgenyChernyi.telegram-notification-extension.sample-telegram-task.SendTelegramNotification@0
      displayName: 'Send Telegram Notification'
      inputs:
        botToken: '5243205545:AAE9P1XSTX6y6vawii1kMTyd0lEi_35JOEc'
        chats: '-643936003'
        message: 'UNI Front Vue упал при сборке '
        releaseName: true
        releaseRequestedFor: true
      continueOnError: true
      condition: failed()

    ## Copy the client to the staging directory
    - task: CopyFiles@2
      inputs:
        sourceFolder: '$(buildOutputFolder)' 
        contents: '**/*' 
        targetFolder: '$(Build.ArtifactStagingDirectory)'
        cleanTargetFolder: true

    - task: EvgenyChernyi.telegram-notification-extension.sample-telegram-task.SendTelegramNotification@0
      displayName: 'Send Telegram Notification'
      inputs:
        botToken: '5243205545:AAE9P1XSTX6y6vawii1kMTyd0lEi_35JOEc'
        chats: '-643936003'
        message: 'UNI Front Vue упал при копировании '
        releaseName: true
        releaseRequestedFor: true
      continueOnError: true
      condition: failed()

    ## Archive the files into a zip file for publishing
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: $(Build.ArtifactStagingDirectory)
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        includeRootFolder: false

    - task: EvgenyChernyi.telegram-notification-extension.sample-telegram-task.SendTelegramNotification@0
      displayName: 'Send Telegram Notification'
      inputs:
        botToken: '5243205545:AAE9P1XSTX6y6vawii1kMTyd0lEi_35JOEc'
        chats: '-643936003'
        message: 'UNI Front Vue упал при архивации'
        releaseName: true
        releaseRequestedFor: true
      continueOnError: true
      condition: failed()

    ## Publish the zip file
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'

    - task: EvgenyChernyi.telegram-notification-extension.sample-telegram-task.SendTelegramNotification@0
      displayName: 'Send Telegram Notification'
      inputs:
        botToken: '5243205545:AAE9P1XSTX6y6vawii1kMTyd0lEi_35JOEc'
        chats: '-643936003'
        message: 'UNI Front Vue упал при публикации артифактов'
        releaseName: true
        releaseRequestedFor: true
      continueOnError: true
      condition: failed()

    - task: EvgenyChernyi.telegram-notification-extension.sample-telegram-task.SendTelegramNotification@0
      displayName: 'Копия Копия Копия Копия Send Telegram Notification'
      inputs:
        botToken: '5243205545:AAE9P1XSTX6y6vawii1kMTyd0lEi_35JOEc'
        chats: '-643936003'
        message: 'UNI Front Vue сборка удачна'
        releaseName: true
        releaseRequestedFor: true
      continueOnError: true


